# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/oneplus5/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/oneplus/oneplus5/proprietary/bin/wfdservice:system/bin/wfdservice \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_10_0.fw:system/etc/firmware/cpp_firmware_v1_10_0.fw \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_12_0.fw:system/etc/firmware/cpp_firmware_v1_12_0.fw \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_5_0.fw:system/etc/firmware/cpp_firmware_v1_5_0.fw \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_5_1.fw:system/etc/firmware/cpp_firmware_v1_5_1.fw \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_5_2.fw:system/etc/firmware/cpp_firmware_v1_5_2.fw \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw \
    vendor/oneplus/oneplus5/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:system/etc/firmware/cpp_firmware_v1_8_0.fw \
    vendor/oneplus/oneplus5/proprietary/etc/init/wfdservice.rc:system/etc/init/wfdservice.rc \
    vendor/oneplus/oneplus5/proprietary/etc/nfcee_access.xml:system/etc/nfcee_access.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/com.nxp.nfc.xml:system/etc/permissions/com.nxp.nfc.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/com.qti.snapdragon.sdk.display.xml:system/etc/permissions/com.qti.snapdragon.sdk.display.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/com.qualcomm.qti.imscmservice.xml:system/etc/permissions/com.qualcomm.qti.imscmservice.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/privapp-permissions-com.qualcomm.location.xml:system/etc/permissions/privapp-permissions-com.qualcomm.location.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/privapp-permissions-qti.xml:system/etc/permissions/privapp-permissions-qti.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/oneplus/oneplus5/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/oneplus/oneplus5/proprietary/etc/wfdconfig.xml:system/etc/wfdconfig.xml \
    vendor/oneplus/oneplus5/proprietary/etc/wfdconfigsink.xml:system/etc/wfdconfigsink.xml \
    vendor/oneplus/oneplus5/proprietary/lib/android.hardware.secure_element@1.0.so:system/lib/android.hardware.secure_element@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/com.qualcomm.qti.ant@1.0.so:system/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/com.qualcomm.qti.bluetooth_audio@1.0.so:system/lib/com.qualcomm.qti.bluetooth_audio@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/com.qualcomm.qti.imscmservice@1.0.so:system/lib/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/com.qualcomm.qti.wifidisplayhal@1.0.so:system/lib/com.qualcomm.qti.wifidisplayhal@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/ese_spi_nxp.so:system/lib/ese_spi_nxp.so \
    vendor/oneplus/oneplus5/proprietary/lib/libaacwrapper.so:system/lib/libaacwrapper.so \
    vendor/oneplus/oneplus5/proprietary/lib/libdisplayconfig.so:system/lib/libdisplayconfig.so \
    vendor/oneplus/oneplus5/proprietary/lib/libldacBT_abr.so:system/lib/libldacBT_abr.so \
    vendor/oneplus/oneplus5/proprietary/lib/libldacBT_enc.so:system/lib/libldacBT_enc.so \
    vendor/oneplus/oneplus5/proprietary/lib/libnl.so:system/lib/libnl.so \
    vendor/oneplus/oneplus5/proprietary/lib/libnxpnfc-nci.so:system/lib/libnxpnfc-nci.so \
    vendor/oneplus/oneplus5/proprietary/lib/libqdMetaData.system.so:system/lib/libqdMetaData.system.so \
    vendor/oneplus/oneplus5/proprietary/lib/libqti-at.so:system/lib/libqti-at.so \
    vendor/oneplus/oneplus5/proprietary/lib/libqti-perfd-client_system.so:system/lib/libqti-perfd-client_system.so \
    vendor/oneplus/oneplus5/proprietary/lib/libqti-util_system.so:system/lib/libqti-util_system.so \
    vendor/oneplus/oneplus5/proprietary/lib/libqti_performance.so:system/lib/libqti_performance.so \
    vendor/oneplus/oneplus5/proprietary/lib/libstagefright_soft_flacdec.so:system/lib/libstagefright_soft_flacdec.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdavenhancements.so:system/lib/libwfdavenhancements.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdclient.so:system/lib/libwfdclient.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdcodecv4l2.so:system/lib/libwfdcodecv4l2.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdconfigutils.so:system/lib/libwfdconfigutils.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdmminterface.so:system/lib/libwfdmminterface.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdmmsink.so:system/lib/libwfdmmsink.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdmmsrc.so:system/lib/libwfdmmsrc.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdnative.so:system/lib/libwfdnative.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdrtsp.so:system/lib/libwfdrtsp.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdservice.so:system/lib/libwfdservice.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfdsm.so:system/lib/libwfdsm.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfduibcsink.so:system/lib/libwfduibcsink.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfduibcsinkinterface.so:system/lib/libwfduibcsinkinterface.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
    vendor/oneplus/oneplus5/proprietary/lib/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
    vendor/oneplus/oneplus5/proprietary/lib/rfsa/adsp/libsns_low_lat_stream_skel.so:system/lib/rfsa/adsp/libsns_low_lat_stream_skel.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.display.color@1.0.so:system/lib/vendor.display.color@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.nxp.nxpese@1.0.so:system/lib/vendor.nxp.nxpese@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.nxp.nxpnfc@1.0.so:system/lib/vendor.nxp.nxpnfc@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.esepowermanager@1.0.so:system/lib/vendor.qti.esepowermanager@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.gnss@1.0.so:system/lib/vendor.qti.gnss@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.gnss@1.1.so:system/lib/vendor.qti.gnss@1.1.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.gnss@1.2.so:system/lib/vendor.qti.gnss@1.2.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.camera.device@1.0.so:system/lib/vendor.qti.hardware.camera.device@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.fm@1.0.so:system/lib/vendor.qti.hardware.fm@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.iop@1.0.so:system/lib/vendor.qti.hardware.iop@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.iop@2.0.so:system/lib/vendor.qti.hardware.iop@2.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.perf@1.0.so:system/lib/vendor.qti.hardware.perf@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.qdutils_disp@1.0.so:system/lib/vendor.qti.hardware.qdutils_disp@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.qteeconnector@1.0.so:system/lib/vendor.qti.hardware.qteeconnector@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.scve.objecttracker@1.0-adapter-helper.so:system/lib/vendor.qti.hardware.scve.objecttracker@1.0-adapter-helper.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.scve.objecttracker@1.0.so:system/lib/vendor.qti.hardware.scve.objecttracker@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.scve.panorama@1.0-adapter-helper.so:system/lib/vendor.qti.hardware.scve.panorama@1.0-adapter-helper.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.scve.panorama@1.0.so:system/lib/vendor.qti.hardware.scve.panorama@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.tui_comm@1.0.so:system/lib/vendor.qti.hardware.tui_comm@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.vpp@1.1.so:system/lib/vendor.qti.hardware.vpp@1.1.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.imsrtpservice@1.0.so:system/lib/vendor.qti.imsrtpservice@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/android.hardware.secure_element@1.0.so:system/lib64/android.hardware.secure_element@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/com.qualcomm.qti.ant@1.0.so:system/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/com.qualcomm.qti.bluetooth_audio@1.0.so:system/lib64/com.qualcomm.qti.bluetooth_audio@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/com.qualcomm.qti.imscmservice@1.0.so:system/lib64/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/ese_spi_nxp.so:system/lib64/ese_spi_nxp.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libaptXHD_encoder.so:system/lib64/libaptXHD_encoder.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libaptX_encoder.so:system/lib64/libaptX_encoder.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libdisplayconfig.so:system/lib64/libdisplayconfig.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libldacBT_abr.so:system/lib64/libldacBT_abr.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libldacBT_enc.so:system/lib64/libldacBT_enc.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libnxpnfc-nci.so:system/lib64/libnxpnfc-nci.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libnxpnfc_nci_jni.so:system/lib64/libnxpnfc_nci_jni.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libqdMetaData.system.so:system/lib64/libqdMetaData.system.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libqti-at.so:system/lib64/libqti-at.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libqti-perfd-client_system.so:system/lib64/libqti-perfd-client_system.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libqti-util_system.so:system/lib64/libqti-util_system.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libqti_performance.so:system/lib64/libqti_performance.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libwfdclient.so:system/lib64/libwfdclient.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libwfdnative.so:system/lib64/libwfdnative.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.display.color@1.0.so:system/lib64/vendor.display.color@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.nxp.nxpese@1.0.so:system/lib64/vendor.nxp.nxpese@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.nxp.nxpnfc@1.0.so:system/lib64/vendor.nxp.nxpnfc@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.esepowermanager@1.0.so:system/lib64/vendor.qti.esepowermanager@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.gnss@1.0.so:system/lib64/vendor.qti.gnss@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.gnss@1.1.so:system/lib64/vendor.qti.gnss@1.1.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.gnss@1.2.so:system/lib64/vendor.qti.gnss@1.2.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.camera.device@1.0.so:system/lib64/vendor.qti.hardware.camera.device@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.data.latency@1.0.so:system/lib64/vendor.qti.hardware.data.latency@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.fm@1.0.so:system/lib64/vendor.qti.hardware.fm@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.iop@1.0.so:system/lib64/vendor.qti.hardware.iop@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.iop@2.0.so:system/lib64/vendor.qti.hardware.iop@2.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.perf@1.0.so:system/lib64/vendor.qti.hardware.perf@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.qdutils_disp@1.0.so:system/lib64/vendor.qti.hardware.qdutils_disp@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.qteeconnector@1.0.so:system/lib64/vendor.qti.hardware.qteeconnector@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.scve.objecttracker@1.0-adapter-helper.so:system/lib64/vendor.qti.hardware.scve.objecttracker@1.0-adapter-helper.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.scve.objecttracker@1.0.so:system/lib64/vendor.qti.hardware.scve.objecttracker@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.scve.panorama@1.0-adapter-helper.so:system/lib64/vendor.qti.hardware.scve.panorama@1.0-adapter-helper.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.scve.panorama@1.0.so:system/lib64/vendor.qti.hardware.scve.panorama@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.tui_comm@1.0.so:system/lib64/vendor.qti.hardware.tui_comm@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.vpp@1.1.so:system/lib64/vendor.qti.hardware.vpp@1.1.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.wifi.keystore@1.0.so:system/lib64/vendor.qti.hardware.wifi.keystore@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so

PRODUCT_PACKAGES += \
    NxpNfcNci \
    NxpSecureElement \
    IFAAService \
    WfdService \
    WfdCommon \
    com.nxp.nfc

ifeq ($(QCPATH),)
PRODUCT_COPY_FILES += \
    vendor/oneplus/oneplus5/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/oneplus/oneplus5/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/oneplus/oneplus5/proprietary/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/audiosphere.xml:system/etc/permissions/audiosphere.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/com.qualcomm.qti.imscmservice.xml:system/etc/permissions/com.qualcomm.qti.imscmservice.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/izat.xt.srv.xml:system/etc/permissions/izat.xt.srv.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/oneplus/oneplus5/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/oneplus/oneplus5/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/oneplus/oneplus5/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/oneplus/oneplus5/proprietary/framework/audiosphere.jar:system/framework/audiosphere.jar \
    vendor/oneplus/oneplus5/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/oneplus/oneplus5/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar \
    vendor/oneplus/oneplus5/proprietary/framework/com.quicinc.cne.api-V1.0-java.jar:system/framework/com.quicinc.cne.api-V1.0-java.jar \
    vendor/oneplus/oneplus5/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/oneplus/oneplus5/proprietary/framework/dpm.jar:system/framework/dpm.jar \
    vendor/oneplus/oneplus5/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/oneplus/oneplus5/proprietary/framework/embmslibrary.jar:system/framework/embmslibrary.jar \
    vendor/oneplus/oneplus5/proprietary/framework/izat.xt.srv.jar:system/framework/izat.xt.srv.jar \
    vendor/oneplus/oneplus5/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/oneplus/oneplus5/proprietary/lib/com.qualcomm.qti.ant@1.0.so:system/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/com.qualcomm.qti.imscmservice@1.0.so:system/lib/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/lib-imscamera.so:system/lib/lib-imscamera.so \
    vendor/oneplus/oneplus5/proprietary/lib/lib-imsvideocodec.so:system/lib/lib-imsvideocodec.so \
    vendor/oneplus/oneplus5/proprietary/lib/lib-imsvtextutils.so:system/lib/lib-imsvtextutils.so \
    vendor/oneplus/oneplus5/proprietary/lib/lib-imsvtutils.so:system/lib/lib-imsvtutils.so \
    vendor/oneplus/oneplus5/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
    vendor/oneplus/oneplus5/proprietary/lib/libGPTEE_system.so:system/lib/libGPTEE_system.so \
    vendor/oneplus/oneplus5/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
    vendor/oneplus/oneplus5/proprietary/lib/libQTEEConnector_system.so:system/lib/libQTEEConnector_system.so \
    vendor/oneplus/oneplus5/proprietary/lib/libantradio.so:system/lib/libantradio.so \
    vendor/oneplus/oneplus5/proprietary/lib/libdiag_system.so:system/lib/libdiag_system.so \
    vendor/oneplus/oneplus5/proprietary/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/oneplus/oneplus5/proprietary/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/oneplus/oneplus5/proprietary/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/oneplus/oneplus5/proprietary/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/oneplus/oneplus5/proprietary/lib/libimscamera_jni.so:system/lib/libimscamera_jni.so \
    vendor/oneplus/oneplus5/proprietary/lib/libimsmedia_jni.so:system/lib/libimsmedia_jni.so \
    vendor/oneplus/oneplus5/proprietary/lib/liblocationservice_jni.so:system/lib/liblocationservice_jni.so \
    vendor/oneplus/oneplus5/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/oneplus/oneplus5/proprietary/lib/libmmparser_lite.so:system/lib/libmmparser_lite.so \
    vendor/oneplus/oneplus5/proprietary/lib/libmmrtpdecoder.so:system/lib/libmmrtpdecoder.so \
    vendor/oneplus/oneplus5/proprietary/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
    vendor/oneplus/oneplus5/proprietary/lib/libqmi_cci_system.so:system/lib/libqmi_cci_system.so \
    vendor/oneplus/oneplus5/proprietary/lib/librcc.so:system/lib/librcc.so \
    vendor/oneplus/oneplus5/proprietary/lib/libsdm-disp-apis.so:system/lib/libsdm-disp-apis.so \
    vendor/oneplus/oneplus5/proprietary/lib/libsecureui_svcsock_system.so:system/lib/libsecureui_svcsock_system.so \
    vendor/oneplus/oneplus5/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/oneplus/oneplus5/proprietary/lib/libsns_low_lat_stream_stub.so:system/lib/libsns_low_lat_stream_stub.so \
    vendor/oneplus/oneplus5/proprietary/lib/libxt_native.so:system/lib/libxt_native.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.display.postproc@1.0.so:system/lib/vendor.display.postproc@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.esepowermanager@1.0.so:system/lib/vendor.qti.esepowermanager@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.gnss@1.0.so:system/lib/vendor.qti.gnss@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.fm@1.0.so:system/lib/vendor.qti.hardware.fm@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.iop@1.0.so:system/lib/vendor.qti.hardware.iop@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.perf@1.0.so:system/lib/vendor.qti.hardware.perf@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.qdutils_disp@1.0.so:system/lib/vendor.qti.hardware.qdutils_disp@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.qteeconnector@1.0.so:system/lib/vendor.qti.hardware.qteeconnector@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.tui_comm@1.0.so:system/lib/vendor.qti.hardware.tui_comm@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.hardware.vpp@1.1.so:system/lib/vendor.qti.hardware.vpp@1.1.so \
    vendor/oneplus/oneplus5/proprietary/lib/vendor.qti.imsrtpservice@1.0.so:system/lib/vendor.qti.imsrtpservice@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/com.qualcomm.qti.ant@1.0.so:system/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/com.qualcomm.qti.imscmservice@1.0.so:system/lib64/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/lib-imscamera.so:system/lib64/lib-imscamera.so \
    vendor/oneplus/oneplus5/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/oneplus/oneplus5/proprietary/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/oneplus/oneplus5/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/oneplus/oneplus5/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libFileMux.so:system/lib64/libFileMux.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libGPTEE_system.so:system/lib64/libGPTEE_system.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libOmxMux.so:system/lib64/libOmxMux.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libQTEEConnector_system.so:system/lib64/libQTEEConnector_system.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libantradio.so:system/lib64/libantradio.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/oneplus/oneplus5/proprietary/lib64/liblocationservice_jni.so:system/lib64/liblocationservice_jni.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libmmosal.so:system/lib64/libmmosal.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libmmparser_lite.so:system/lib64/libmmparser_lite.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libmmrtpdecoder.so:system/lib64/libmmrtpdecoder.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libmmrtpencoder.so:system/lib64/libmmrtpencoder.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libqmi_cci_system.so:system/lib64/libqmi_cci_system.so \
    vendor/oneplus/oneplus5/proprietary/lib64/librcc.so:system/lib64/librcc.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libsdm-disp-apis.so:system/lib64/libsdm-disp-apis.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libsecureui_svcsock_system.so:system/lib64/libsecureui_svcsock_system.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libsensor1.so:system/lib64/libsensor1.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libsns_low_lat_stream_stub.so:system/lib64/libsns_low_lat_stream_stub.so \
    vendor/oneplus/oneplus5/proprietary/lib64/libxt_native.so:system/lib64/libxt_native.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.display.postproc@1.0.so:system/lib64/vendor.display.postproc@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.esepowermanager@1.0.so:system/lib64/vendor.qti.esepowermanager@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.gnss@1.0.so:system/lib64/vendor.qti.gnss@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.data.latency@1.0.so:system/lib64/vendor.qti.hardware.data.latency@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.fm@1.0.so:system/lib64/vendor.qti.hardware.fm@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.perf@1.0.so:system/lib64/vendor.qti.hardware.perf@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.qdutils_disp@1.0.so:system/lib64/vendor.qti.hardware.qdutils_disp@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.qteeconnector@1.0.so:system/lib64/vendor.qti.hardware.qteeconnector@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.tui_comm@1.0.so:system/lib64/vendor.qti.hardware.tui_comm@1.0.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.hardware.vpp@1.1.so:system/lib64/vendor.qti.hardware.vpp@1.1.so \
    vendor/oneplus/oneplus5/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so

PRODUCT_PACKAGES += \
    AntHalService \
    QtiSystemService \
    QtiTelephonyService \
    datastatusnotification \
    embms \
    ims \
    imssettings \
    CNEService \
    com.qualcomm.location \
    dpmserviceapp \
    qcrilmsgtunnel \
    com.qti.dpmframework \
    com.qti.snapdragon.sdk.display \
    qcnvitems \
    qcrilhook \
    qti-telephony-common
endif

-include vendor/extra/devices.mk
ifneq ($(call is-qc-perf-target),true)
endif
